### PR TITLE
initial attempt at adding proper cri-o support

### LINKED ISSUE #15: All manifests end up under docker.io path in S3
In S3, I only have a `docker.io` path:

image

If you look in logs too for requests to other registries, it is specifically looking under `docker.io`, even for registries that aren't `docker.io`:
```
crictl pull quay.io/kiwigrid/k8s-sidecar:1.25.1
Image is up to date for quay.io/kiwigrid/k8s-sidecar@sha256:415d07ee1027c3ff7af9e26e05e03ffd0ec0ccf9f619ac00ab24366efe4343bd
```

Results in:
```
oci-registry-5b5495cc57-vbpvb oci-registry 2023-09-29T18:35:36.035138Z  INFO actix_web::middleware::logger: 10.70.134.38 "GET /v2/ HTTP/1.1" 200 0 "-" "cri-o/1.25.4 go/go1.19 os/linux arch/amd64" 0.136317
oci-registry-5b5495cc57-vbpvb oci-registry 2023-09-29T18:35:36.150080Z  WARN oci_registry::api: /kiwigrid/k8s-sidecar/manifests/1.25.1 not found at manifests/docker.io/kiwigrid/k8s-sidecar/1.25.1 in repository (Failed to get object from S3: Service(NoSuchKey("The specified key does not exist."))); pulling from upstream
oci-registry-5b5495cc57-vbpvb oci-registry 2023-09-29T18:35:36.304660Z  INFO actix_web::middleware::logger: 10.70.134.38 "GET /v2/kiwigrid/k8s-sidecar/manifests/1.25.1 HTTP/1.1" 200 3893 "-" "cri-o/1.25.4 go/go1.19 os/linux arch/amd64" 0.267325
oci-registry-5b5495cc57-58ltl oci-registry 2023-09-29T18:35:36.376593Z  WARN oci_registry::api: /kiwigrid/k8s-sidecar/manifests/sha256:f929c7fc94605cd51af74ab7941d7982ce94ab904ea032868026633a3435682a not found at manifests/docker.io/kiwigrid/k8s-sidecar/sha256:f929c7fc94605cd51af74ab7941d7982ce94ab904ea032868026633a3435682a in repository (Failed to get object from S3: Service(NoSuchKey("The specified key does not exist."))); pulling from upstream
oci-registry-5b5495cc57-58ltl oci-registry 2023-09-29T18:35:36.525244Z  INFO actix_web::middleware::logger: 10.70.134.38 "GET /v2/kiwigrid/k8s-sidecar/manifests/sha256:f929c7fc94605cd51af74ab7941d7982ce94ab904ea032868026633a3435682a HTTP/1.1" 200 1624 "-" "cri-o/1.25.4 go/go1.19 os/linux arch/amd64" 0.218926
```

oci-registry version v0.3.20

crio version 1.25.4

Here's my config:
```
data:
  upstream.yaml: |
    - host: registry-1.docker.io
      namespace: docker.io
      password: PASSWORD
      username: USERNAME
    - host: quay.io
      namespace: quay.io
    - host: gcr.io
      namespace: gcr.io
    - host: ghcr.io
      namespace: ghcr.io
    - host: k8s.gcr.io
      namespace: k8s.gcr.io
    - host: registry.k8s.io
      namespace: registry.k8s.io
    - host: public.ecr.aws
      namespace: public.ecr.aws
```

### LINKED ISSUE #16: Certain registries not working
It seems certain registries (or even certain images in certain registries) don't play well with `oci-registry`:

`quay.io`:
```
crictl pull quay.io/prometheus-operator/prometheus-config-reloader:v0.62.0
Image is up to date for quay.io/prometheus-operator/prometheus-config-reloader@sha256:267b12235d10a810e49b2d40a3deda6256f92690b26997a199601a47283821b9
```

```
oci-registry-5b5495cc57-58ltl oci-registry 2023-09-29T18:40:11.946961Z  INFO actix_web::middleware::logger: 10.70.134.38 "GET /v2/ HTTP/1.1" 200 0 "-" "cri-o/1.25.4 go/go1.19 os/linux arch/amd64" 0.060383
oci-registry-5b5495cc57-vbpvb oci-registry 2023-09-29T18:40:11.993737Z  WARN oci_registry::api: /prometheus-operator/prometheus-config-reloader/manifests/v0.62.0 not found at manifests/docker.io/prometheus-operator/prometheus-config-reloader/v0.62.0 in repository (Failed to get object from S3: Service(NoSuchKey("The specified key does not exist."))); pulling from upstream
oci-registry-5b5495cc57-vbpvb oci-registry 2023-09-29T18:40:12.095411Z ERROR oci_registry::api::error: 500: Error with upstream registry: unexpected HTTP status 401 Unauthorized
oci-registry-5b5495cc57-vbpvb oci-registry 2023-09-29T18:40:12.095454Z  INFO actix_web::middleware::logger: 10.70.134.38 "GET /v2/prometheus-operator/prometheus-config-reloader/manifests/v0.62.0 HTTP/1.1" 500 69 "-" "cri-o/1.25.4 go/go1.19 os/linux arch/amd64" 0.146511
```

The weird thing about `quay.io` though is that _some_ images work:
```
crictl pull quay.io/kiwigrid/k8s-sidecar:1.25.1
Image is up to date for quay.io/kiwigrid/k8s-sidecar@sha256:415d07ee1027c3ff7af9e26e05e03ffd0ec0ccf9f619ac00ab24366efe4343bd
```

```
oci-registry-5b5495cc57-vbpvb oci-registry 2023-09-29T18:42:05.363620Z  INFO actix_web::middleware::logger: 10.70.134.38 "GET /v2/ HTTP/1.1" 200 0 "-" "cri-o/1.25.4 go/go1.19 os/linux arch/amd64" 0.064244
oci-registry-5b5495cc57-vbpvb oci-registry 2023-09-29T18:42:05.436969Z  INFO actix_web::middleware::logger: 10.70.134.38 "GET /v2/kiwigrid/k8s-sidecar/manifests/1.25.1 HTTP/1.1" 200 3893 "-" "cri-o/1.25.4 go/go1.19 os/linux arch/amd64" 0.071172
oci-registry-5b5495cc57-58ltl oci-registry 2023-09-29T18:42:05.487533Z  INFO actix_web::middleware::logger: 10.70.134.38 "GET /v2/kiwigrid/k8s-sidecar/manifests/sha256:f929c7fc94605cd51af74ab7941d7982ce94ab904ea032868026633a3435682a HTTP/1.1" 200 1624 "-" "cri-o/1.25.4 go/go1.19 os/linux arch/amd64" 0.048954
```

`ghcr.io`:
```
crictl pull ghcr.io/buildbarn/bb-worker@sha256:759342b5478abd3bc0ad2dbe8e0c57cc11e413e79c631a03288275626e322ffb
Image is up to date for ghcr.io/buildbarn/bb-worker@sha256:759342b5478abd3bc0ad2dbe8e0c57cc11e413e79c631a03288275626e322ffb
```

```
oci-registry-5b5495cc57-vbpvb oci-registry 2023-09-29T18:43:14.869534Z  INFO actix_web::middleware::logger: 10.70.134.38 "GET /v2/ HTTP/1.1" 200 0 "-" "cri-o/1.25.4 go/go1.19 os/linux arch/amd64" 0.060870
oci-registry-5b5495cc57-vbpvb oci-registry 2023-09-29T18:43:14.915455Z  WARN oci_registry::api: /buildbarn/bb-worker/manifests/sha256:759342b5478abd3bc0ad2dbe8e0c57cc11e413e79c631a03288275626e322ffb not found at manifests/docker.io/buildbarn/bb-worker/sha256:759342b5478abd3bc0ad2dbe8e0c57cc11e413e79c631a03288275626e322ffb in repository (Failed to get object from S3: Service(NoSuchKey("The specified key does not exist."))); pulling from upstream
oci-registry-5b5495cc57-vbpvb oci-registry 2023-09-29T18:43:15.023457Z ERROR oci_registry::api::error: 404: Error with upstream registry: unexpected HTTP status 404 Not Found
oci-registry-5b5495cc57-vbpvb oci-registry 2023-09-29T18:43:15.023503Z  INFO actix_web::middleware::logger: 10.70.134.38 "GET /v2/buildbarn/bb-worker/manifests/sha256:759342b5478abd3bc0ad2dbe8e0c57cc11e413e79c631a03288275626e322ffb HTTP/1.1" 404 66 "-" "cri-o/1.25.4 go/go1.19 os/linux arch/amd64" 0.151947
```

`registry.k8s.io`:
```
crictl pull registry.k8s.io/sig-storage/livenessprobe:v2.3.0
Image is up to date for registry.k8s.io/sig-storage/livenessprobe@sha256:1b7c978a792a8fa4e96244e8059bd71bb49b07e2e5a897fb0c867bdc6db20d5d
```

```
oci-registry-5b5495cc57-vbpvb oci-registry 2023-09-29T18:43:38.450828Z  INFO actix_web::middleware::logger: 10.70.134.38 "GET /v2/ HTTP/1.1" 200 0 "-" "cri-o/1.25.4 go/go1.19 os/linux arch/amd64" 0.085598
oci-registry-5b5495cc57-vbpvb oci-registry 2023-09-29T18:43:38.497768Z  WARN oci_registry::api: /sig-storage/livenessprobe/manifests/v2.3.0 not found at manifests/docker.io/sig-storage/livenessprobe/v2.3.0 in repository (Failed to get object from S3: Service(NoSuchKey("The specified key does not exist."))); pulling from upstream
oci-registry-5b5495cc57-vbpvb oci-registry 2023-09-29T18:43:38.588364Z ERROR oci_registry::api::error: 500: Error with upstream registry: unexpected HTTP status 401 Unauthorized
oci-registry-5b5495cc57-vbpvb oci-registry 2023-09-29T18:43:38.588399Z  INFO actix_web::middleware::logger: 10.70.134.38 "GET /v2/sig-storage/livenessprobe/manifests/v2.3.0 HTTP/1.1" 500 69 "-" "cri-o/1.25.4 go/go1.19 os/linux arch/amd64" 0.135313
```

`public.ecr.aws`:
```
crictl pull public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe:v2.10.0-eks-1-27-7
Image is up to date for public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe@sha256:1bc2f27283fd1d02a82bf0f9d12f2ecf62051798ad43ac28d38f8ca13fa50fea
```

```
oci-registry-5b5495cc57-vbpvb oci-registry 2023-09-29T18:44:09.776823Z  INFO actix_web::middleware::logger: 10.70.134.38 "GET /v2/ HTTP/1.1" 200 0 "-" "cri-o/1.25.4 go/go1.19 os/linux arch/amd64" 0.067996
oci-registry-5b5495cc57-vbpvb oci-registry 2023-09-29T18:44:09.830132Z  WARN oci_registry::api: /eks-distro/kubernetes-csi/livenessprobe/manifests/v2.10.0-eks-1-27-7 not found at manifests/docker.io/eks-distro/kubernetes-csi/livenessprobe/v2.10.0-eks-1-27-7 in repository (Failed to get object from S3: Service(NoSuchKey("The specified key does not exist."))); pulling from upstream
oci-registry-5b5495cc57-vbpvb oci-registry 2023-09-29T18:44:09.885588Z ERROR oci_registry::api::error: 500: Error with upstream registry: unexpected HTTP status 401 Unauthorized
oci-registry-5b5495cc57-vbpvb oci-registry 2023-09-29T18:44:09.885624Z  INFO actix_web::middleware::logger: 10.70.134.38 "GET /v2/eks-distro/kubernetes-csi/livenessprobe/manifests/v2.10.0-eks-1-27-7 HTTP/1.1" 500 69 "-" "cri-o/1.25.4 go/go1.19 os/linux arch/amd64" 0.106557
```

oci-registry version v0.3.20

crio version 1.25.4

Here's my config:
```
data:
  upstream.yaml: |
    - host: registry-1.docker.io
      namespace: docker.io
      password: PASSWORD
      username: USERNAME
    - host: quay.io
      namespace: quay.io
    - host: gcr.io
      namespace: gcr.io
    - host: ghcr.io
      namespace: ghcr.io
    - host: k8s.gcr.io
      namespace: k8s.gcr.io
    - host: registry.k8s.io
      namespace: registry.k8s.io
    - host: public.ecr.aws
      namespace: public.ecr.aws
```

### PR DESCRIPTION
**Pull request by com6056**
Fixes #15
Fixes #16

This adds support for paths that have a path prefix of the namespace instead of the `ns` param.

Tested using the new simple test script I added in:
```
./test.sh
--- Testing docker.io/envoyproxy/envoy/manifests/v1.26.2
  200: localhost:8080/v2/envoyproxy/envoy/manifests/v1.26.2?ns=docker.io
  200: localhost:8080/v2/docker.io/envoyproxy/envoy/manifests/v1.26.2
  200: localhost:8080/v2/envoyproxy/envoy/manifests/v1.26.2
--- Testing docker.io/library/busybox/manifests/latest
  200: localhost:8080/v2/library/busybox/manifests/latest?ns=docker.io
  200: localhost:8080/v2/docker.io/library/busybox/manifests/latest
  200: localhost:8080/v2/library/busybox/manifests/latest
--- Testing docker.io/grafana/mimirtool/blobs/sha256:31e352740f534f9ad170f75378a84fe453d6156e40700b882d737a8f4a6988a3
  200: localhost:8080/v2/grafana/mimirtool/blobs/sha256:31e352740f534f9ad170f75378a84fe453d6156e40700b882d737a8f4a6988a3?ns=docker.io
  200: localhost:8080/v2/docker.io/grafana/mimirtool/blobs/sha256:31e352740f534f9ad170f75378a84fe453d6156e40700b882d737a8f4a6988a3
  200: localhost:8080/v2/grafana/mimirtool/blobs/sha256:31e352740f534f9ad170f75378a84fe453d6156e40700b882d737a8f4a6988a3
--- Testing gcr.io/distroless/static/manifests/latest
  200: localhost:8080/v2/distroless/static/manifests/latest?ns=gcr.io
  200: localhost:8080/v2/gcr.io/distroless/static/manifests/latest
--- Testing gcr.io/distroless/static/blobs/sha256:fe5ca62666f04366c8e7f605aa82997d71320183e99962fa76b3209fdfbb8b58
  200: localhost:8080/v2/distroless/static/blobs/sha256:fe5ca62666f04366c8e7f605aa82997d71320183e99962fa76b3209fdfbb8b58?ns=gcr.io
  200: localhost:8080/v2/gcr.io/distroless/static/blobs/sha256:fe5ca62666f04366c8e7f605aa82997d71320183e99962fa76b3209fdfbb8b58
--- Testing gcr.io/flame-public/buildbuddy-app-onprem/manifests/sha256:68932b6227b4c16d6bbc08997620284ef71f7b10ee9b9dc47b631ae92f31a6a3
  200: localhost:8080/v2/flame-public/buildbuddy-app-onprem/manifests/sha256:68932b6227b4c16d6bbc08997620284ef71f7b10ee9b9dc47b631ae92f31a6a3?ns=gcr.io
  200: localhost:8080/v2/gcr.io/flame-public/buildbuddy-app-onprem/manifests/sha256:68932b6227b4c16d6bbc08997620284ef71f7b10ee9b9dc47b631ae92f31a6a3
--- Testing ghcr.io/buildbarn/bb-runner-installer/manifests/sha256:beb72a39662a613a889f17e7a15254f7e03849e4f7000f399ea7bdabe4a25f79
  200: localhost:8080/v2/buildbarn/bb-runner-installer/manifests/sha256:beb72a39662a613a889f17e7a15254f7e03849e4f7000f399ea7bdabe4a25f79?ns=ghcr.io
  200: localhost:8080/v2/ghcr.io/buildbarn/bb-runner-installer/manifests/sha256:beb72a39662a613a889f17e7a15254f7e03849e4f7000f399ea7bdabe4a25f79
--- Testing ghcr.io/buildbarn/bb-runner-installer/blobs/sha256:e2334dd9fee4b77e48a8f2d793904118a3acf26f1f2e72a3d79c6cae993e07f0
  200: localhost:8080/v2/buildbarn/bb-runner-installer/blobs/sha256:e2334dd9fee4b77e48a8f2d793904118a3acf26f1f2e72a3d79c6cae993e07f0?ns=ghcr.io
  200: localhost:8080/v2/ghcr.io/buildbarn/bb-runner-installer/blobs/sha256:e2334dd9fee4b77e48a8f2d793904118a3acf26f1f2e72a3d79c6cae993e07f0
```

The directory layout is now fixed as well 🎉 
```
tree /tmp/oci-mirror
/tmp/oci-mirror
├── blobs
│   └── sha256
│       ├── 31
│       │   └── e352740f534f9ad170f75378a84fe453d6156e40700b882d737a8f4a6988a3
│       ├── e2
│       │   └── 334dd9fee4b77e48a8f2d793904118a3acf26f1f2e72a3d79c6cae993e07f0
│       └── fe
│           └── 5ca62666f04366c8e7f605aa82997d71320183e99962fa76b3209fdfbb8b58
└── manifests
    ├── docker.io
    │   ├── envoyproxy
    │   │   └── envoy
    │   │       └── v1.26.2
    │   └── library
    │       └── busybox
    │           └── latest
    ├── gcr.io
    │   ├── distroless
    │   │   └── static
    │   │       └── latest
    │   └── flame-public
    │       └── buildbuddy-app-onprem
    │           └── sha256:68932b6227b4c16d6bbc08997620284ef71f7b10ee9b9dc47b631ae92f31a6a3
    └── ghcr.io
        └── buildbarn
            └── bb-runner-installer
                └── sha256:beb72a39662a613a889f17e7a15254f7e03849e4f7000f399ea7bdabe4a25f79

20 directories, 8 files
```

### CODE REVIEW

File: src/api.rs [hunk 1]
```diff
@@ -64,6 +64,9 @@ impl ManifestRequest {
 	}
 
 	fn storage_path(&self, ns: &str) -> String {
+		if ns == self.image.as_ref().split("/").next().unwrap_or_default() {
+			return format!("manifests/{}/{}", self.image, self.reference);
+		}
 		format!("manifests/{}/{}/{}", ns, self.image, self.reference)
```
Comment (mcronce) [inline src/api.rs]: I would use a match here, as well as `splitn` and a char instead of str, something like
```suggestion
		match self.image.as_ref().splitn(2, '/').next() {
			Some(part) if part == ns => format!("manifests/{}/{}", self.image, self.reference),
			_ => format!("manifests/{}/{}/{}", ns, self.image, self.reference
			// Some(_) | None => format!("manifests/{}/{}/{}", ns, self.image, self.reference would also work
		}
```

It likely compiles down to identical bytecode (with the possible exception of using `'/'` instead of `"/"`), but this is more idiomatic/common Rust code

File: src/api.rs [hunk 2]
```diff
@@ -86,8 +89,12 @@ pub async fn manifest(req: web::Path<ManifestRequest>, qstr: web::Query<Manifest
 	static HIT_COUNTER: Lazy<IntCounterVec> = Lazy::new(|| register_int_counter_vec!("manifest_cache_hits", "Number of manifests read from cache", &["namespace"]).unwrap());
 	static MISS_COUNTER: Lazy<IntCounterVec> = Lazy::new(|| register_int_counter_vec!("manifest_cache_misses", "Number of manifest requests that went to upstream", &["namespace"]).unwrap());
 
-	let namespace = qstr.ns.as_deref().unwrap_or_else(|| req.image.as_ref().split("/").next().unwrap_or_else(|| config.default_ns.as_ref()));
+	let mut namespace = qstr.ns.as_deref().unwrap_or_else(|| config.default_ns.as_ref());
+	if req.image.as_ref().split("/").count() > 2 {
+		namespace = req.image.as_ref().split("/").next().unwrap_or_else(|| config.default_ns.as_ref());
+	}
 
+	let image: &str = req.image.as_ref().trim_start_matches("docker.io/");
```
Comment (mcronce) [inline src/api.rs]: Same deal with these - switch `"/"` to `'/'`

You can also avoid the mutable variable with something along these lines:
```suggestion
	let (namespace, image) = match qstr.ns.as_deref() {
		Some(ns) => (ns, req.image.as_ref()),
		None => {
			let mut parts = req.image.splitn(2, '/');
			match (parts.next(), parts.next()) {
				(Some(ns), Some(image)) => (ns, image),
				(Some(image), None) => (config.default_ns.as_ref(), image),
				(None, None) => unreachable!() // maybe want to throw an error here but this is fine for now
			}
		}
	};
```

That should work, modulo any compile errors...and giving the explicit `ns` parameter priority will prevent breaking non-`crio` deployments that have single-segment images

File: src/api.rs [hunk 3]
```diff
@@ -150,8 +157,12 @@ pub async fn blob(req: web::Path<BlobRequest>, qstr: web::Query<ManifestQueryStr
 		return Err(Error::InvalidDigest);
 	}
 
-	let namespace = qstr.ns.as_deref().unwrap_or_else(|| req.image.as_ref().split("/").next().unwrap_or_else(|| config.default_ns.as_ref()));
+	let mut namespace = qstr.ns.as_deref().unwrap_or_else(|| config.default_ns.as_ref());
+	if req.image.as_ref().split("/").count() > 2 {
+		namespace = req.image.as_ref().split("/").next().unwrap_or_else(|| config.default_ns.as_ref());
+	}
 
+	let image: &str = req.image.as_ref().trim_start_matches("docker.io/");
```
Comment (mcronce) [inline src/api.rs]: Same as above here - in fact maybe makes sense to deduplicate that in a helper function.  I don't feel strongly about that though, whatever you feel like doing is fine

**Review by mcronce — CHANGES_REQUESTED** [review]

File: src/api.rs [hunk 4]
```diff
@@ -13,8 +13,8 @@ use futures::stream;
 use futures::StreamExt;
 use futures::TryStreamExt;
 use once_cell::sync::Lazy;
-use prometheus::IntCounterVec;
```
Comment (com6056) [inline src/api.rs:16]: shoot sorry about the whitespace/formatting changes, must have run vscode's formatter, let me know if you want me to undo

Comment (mcronce) [reply src/api.rs:16]: I have a `.rustfmt.toml` in the repo and apparently didn't `cargo fmt` in one of the more recent changesets - this is fine, it follows the config

File: src/api.rs [hunk 5]
```diff
@@ -86,8 +96,21 @@ pub async fn manifest(req: web::Path<ManifestRequest>, qstr: web::Query<Manifest
 	static HIT_COUNTER: Lazy<IntCounterVec> = Lazy::new(|| register_int_counter_vec!("manifest_cache_hits", "Number of manifests read from cache", &["namespace"]).unwrap());
 	static MISS_COUNTER: Lazy<IntCounterVec> = Lazy::new(|| register_int_counter_vec!("manifest_cache_misses", "Number of manifest requests that went to upstream", &["namespace"]).unwrap());
 
-	let max_age = config.upstream.lock().await.get(qstr.ns.as_deref())?.manifest_invalidation_time;
-	let namespace = qstr.ns.as_deref().unwrap_or_else(|| config.default_ns.as_ref());
+	let (namespace, image) = match qstr.ns.as_deref() {
+		Some(ns) => (ns, req.image.as_ref().trim_start_matches(&format!("{}/", ns))),
```
Comment (mcronce) [inline src/api.rs]: Is trimming the namespace from the beginning required when `ns` is passed as an explicit parameter?  I think not trimming it would only cause a problem if someone configured containerd, which supports `?ns=`, but included namespace-prefixed paths - I would consider that a misconfiguration

Comment (com6056) [reply src/api.rs]: That's fair, I figured it didn't hurt to support both being used for some reason but I can clean that up, agree it would likely be a misconfiguration

**Review by mcronce — APPROVED** [review]
